### ISSUE TITLE
When i create a task has recevied a error-404 .

### ISSUE THREAD

**Issue by strongant** [medcl/gopa#1]
![gopa](https://cloud.githubusercontent.com/assets/7685936/21748144/254bb072-d5b8-11e6-82c8-f44453e5c4d0.png)

**Comment by medcl** [comment]
seems some bug, let me dig it,
for now, check out http://127.0.0.1:8001/ui/page/console.html
type `seed elasticsearch.cn`

**Comment by strongant** [comment]
![image](https://cloud.githubusercontent.com/assets/7685936/21748216/8d6a4aa4-d5ba-11e6-8a7b-8f436f912b96.png)
